version: "3"
services:

  hub:
    image: selenium/hub
    ports:
      - "4444:4444"

    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 3000
      GRID_TIMEOUT: 3000

  chrome:
    image: selenium/node-chrome
    container_name: web-automation_chrome
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 16
      NODE_MAX_INSTANCES: 16
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "9001:5900"
    links:
      - hub

  maven:
    image: "maven:3.6.3-jdk-8"
    links:
      - hub
    volumes:
      - "$PWD:/usr/src/mymaven"
      - "$HOME/.m2:/root/.m2"
      - "$PWD/target:/usr/src/mymaven/target"
      - "$PWD/result:/usr/src/mymaven/result"
    command: >
      sh -c "cd /usr/src/mymaven &&
             mvn test -Premote "
